// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa7xxyQ2yB2yF0HKf-P7LNB57g1OgoeHA',
    appId: '1:60706214033:web:e4dbe5a5506cee665b6f30',
    messagingSenderId: '60706214033',
    projectId: 'chatapp-fb0d5',
    authDomain: 'chatapp-fb0d5.firebaseapp.com',
    storageBucket: 'chatapp-fb0d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASfd_nMuvw07PfjZZynq9cisH79VOUm5k',
    appId: '1:60706214033:android:d32e9d3b3bdc40d15b6f30',
    messagingSenderId: '60706214033',
    projectId: 'chatapp-fb0d5',
    storageBucket: 'chatapp-fb0d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkXfB-724wcc0V-3fl45utAeM-WNe5oo0',
    appId: '1:60706214033:ios:aad1d098d4a699fb5b6f30',
    messagingSenderId: '60706214033',
    projectId: 'chatapp-fb0d5',
    storageBucket: 'chatapp-fb0d5.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkXfB-724wcc0V-3fl45utAeM-WNe5oo0',
    appId: '1:60706214033:ios:7476327b2e37f1565b6f30',
    messagingSenderId: '60706214033',
    projectId: 'chatapp-fb0d5',
    storageBucket: 'chatapp-fb0d5.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
